sign-tag = true
# Required for templates below to work.
consolidate-commits = false
pre-release-commit-message = "version {{version}}"
tag-message = "version {{version}}"
tag-name = "byte-wrapper-{{version}}"
publish = false
pre-release-hook = ["just", "generate-readmes"]
